name: deploy-dev-darads-hub-api 🔥🔥🔥🔥
on: 
  push:
    branches:
      - master
env:
  AZURE_WEBAPP_NAME: DaradsHub
  AZURE_WEBAPP_PACKAGE_PATH: "/home/runner/work/DaradsHubAPI/DaradsHubAPI.WebAPI/bin/Release/net8.0/publish/"

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore  ./DaradsHubAPI.sln
        
      - name: Build
        run: dotnet build  ./DaradsHubAPI --configuration Release --no-restore

      - name: Publish
        run:  dotnet publish ./DaradsHubAPI/DaradsHubAPI.WebAPI/DaradsHubAPI.WebAPI.csproj --configuration Release --no-restore 
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
   
